version: '2'

services:

  hdfs-namenode:
    image: sgioldasis/elastest-hadoop:2.8.0
    command: hdfs namenode
    ports: 
        - "50070:50070"
        - "9000:9000"
        - "8020:8020"
    hostname: hdfs-namenode
    networks:
        - elastest

  hdfs-datanode:
    image: sgioldasis/elastest-hadoop:2.8.0
    command: hdfs datanode
    ports:
# The host port is randomly assigned by Docker, to allow scaling to multiple DataNodes on the same host
        - "50075"
    links:
        - hdfs-namenode
    networks:
        - elastest

  alluxio-master:
    # Test automated build when git push
    # build: docker-alluxio-base
    image: sgioldasis/elastest-alluxio:1.5.0
    command: master
    ports:
      - 19999:19999
      - 19998:19998
    #   - 30000:30000
    # volumes:
    #   - data:/data
    environment:
      - ALLUXIO_MASTER_HOSTNAME=alluxio-master
      - ALLUXIO_UNDERFS_ADDRESS=/underStorage
      # - ALLUXIO_UNDERFS_ADDRESS=hdfs://hdfs-namenode:9000
    links:
        - hdfs-namenode
    volumes:
      - ./underStorage:/underStorage
    hostname: alluxio-master
    networks:
        - elastest

  alluxio-worker:
    # build: docker-alluxio-base
    image: sgioldasis/elastest-alluxio:1.5.0
    command: worker
    ports:
      - "29998"
      - "29999"
    links:
      - hdfs-namenode
      - alluxio-master
    # volumes:
    #   - ./tmpfiles:/tmpfiles
    ## change to your DOCKER_HOST
    # hostname: 192.168.99.100

    #    privileged: true         ### enable to use ramfs with docker. otherwise it will use disk
    environment:
      - ALLUXIO_MASTER_HOSTNAME=alluxio-master
      - ALLUXIO_RAM_FOLDER=/mnt/ramdisk
      - ALLUXIO_WORKER_MEMORY_SIZE=1GB
      - ALLUXIO_UNDERFS_ADDRESS=/underStorage
      # - ALLUXIO_UNDERFS_ADDRESS=hdfs://hdfs-namenode:9000
    volumes:
      - ./underStorage:/underStorage
      # - ./tmpfiles:/tmpfiles
    networks:
        - elastest


  alluxio-proxy:
    # build: docker-alluxio-base
    image: sgioldasis/elastest-alluxio:1.5.0
    command: proxy
    ports:
      - 39999:39999
    links:
      - alluxio-worker
    # volumes:
    #   - ./tmpfiles:/tmpfiles
    ## change to your DOCKER_HOST
    # hostname: 192.168.99.100

    #    privileged: true         ### enable to use ramfs with docker. otherwise it will use disk
    environment:
      - ALLUXIO_MASTER_HOSTNAME=alluxio-master
      # - ALLUXIO_RAM_FOLDER=/mnt/ramdisk
      # - ALLUXIO_WORKER_MEMORY_SIZE=1GB
      # - ALLUXIO_UNDERFS_ADDRESS=hdfs://hdfs-namenode:9000
    volumes:
      - ./underStorage:/underStorage
      # - ./tmpfiles:/tmpfiles
    networks:
        - elastest


  elasticsearch:
    # build: elasticsearch/
    image: sgioldasis/elastest-elasticsearch:5.4.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - discovery.type=zen
      # use internal Docker round-robin DNS for unicast discovery
      - discovery.zen.ping.unicast.hosts=elasticsearch
    hostname: elasticsearch
    networks:
      - elastest


  esnode:
    # build: elasticsearch/
    image: sgioldasis/elastest-elasticsearch:5.4.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200"
      - "9300"
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      # use internal Docker round-robin DNS for unicast discovery
      - discovery.type=zen
      - discovery.zen.ping.unicast.hosts=elasticsearch
    hostname: esnode
    networks:
      - elastest


  kibana:
    # build: kibana/
    image: sgioldasis/elastest-kibana:5.4.1
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      # use internal Docker round-robin DNS for unicast discovery
      - discovery.type=zen
      - discovery.zen.ping.unicast.hosts=elasticsearch
    networks:
      - elastest
    depends_on:
      - elasticsearch


  cerebro:
    # container_name: cerebro
    image: sgioldasis/elastest-cerebro:0.6.5
    # build: cerebro/
    volumes:
      - ./cerebro/config/conf:/opt/cerebro-0.6.5/conf
      - ./cerebro/logs:/opt/cerebro-0.6.5/logs
    depends_on:
      - elasticsearch
    ports:
      - 9400:9000
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    tty: true
    networks:
      - elastest
    depends_on:
      - elasticsearch

  mysql:
    image: sgioldasis/elastest-mysql:5.7
    ports:
      - "3306:3306"    
    # container_name: mysql-elastest
    environment:
      MYSQL_ROOT_PASSWORD: "elastestroot"
      MYSQL_DATABASE: "elastest"
      MYSQL_USER: elastest
      MYSQL_PASSWORD: elastest
    volumes:
      - elastest_mysql_data:/var/lib/mysql
      - ./mysql/backup:/docker-entrypoint-initdb.d
    # restart: always
    networks:
      - elastest
 
 
volumes:
  elastest_mysql_data:

networks:
  elastest:
    driver: bridge




## Run everything in one container
#  alluxio-local:
#    build: docker-alluxio-base
#    command: /start.sh local
#    ports:
#      - 19999:19999
#      - 19998:19998
#      - 30000:30000
#      - 29998:29998
#      - 29999:29999
#    ## change to your DOCKER_HOST
#    hostname: 192.168.99.100
#    #    privileged: true         ### enable to use ramfs with docker. otherwise it will use disk
#    volumes:
#      - data:/data
#    environment:
#      ALLUXIO_MASTER_ADDRESS: 192.168.99.100



# volumes:
#   data: