version: '2'

services:

  hdfs-namenode:
    container_name: hdfs-namenode
    image: elastest/edm-hadoop:0.5.0
    # build: ./hadoop
    command: hdfs namenode
    ports: 
        - "50070:50070"
        - "9000:9000"
        - "8020:8020"
    hostname: hdfs-namenode
    networks:
        - elastest

  hdfs-datanode:
    # container_name: hdfs-datanode
    image: elastest/edm-hadoop:0.5.0
    # build: ./hadoop
    command: hdfs datanode
    # The host port is randomly assigned by Docker, 
    # to allow scaling to multiple DataNodes on the same host
    ports:
        - "50075"
    links:
        - hdfs-namenode
    networks:
        - elastest

  alluxio-master:
    container_name: alluxio-master
    image: elastest/edm-alluxio:0.5.0
    # build: ./alluxio
    command: master
    ports:
      - 19999:19999
      - 19998:19998
    #   - 30000:30000
    # volumes:
    #   - data:/data
    environment:
      - ALLUXIO_MASTER_HOSTNAME=alluxio-master
      - ALLUXIO_UNDERFS_ADDRESS=/underStorage
      # - ALLUXIO_UNDERFS_ADDRESS=hdfs://hdfs-namenode:9000
    links:
        - hdfs-namenode
    volumes:
      - ./underStorage:/underStorage
    hostname: alluxio-master
    networks:
        - elastest

  alluxio-worker:
    # container_name: alluxio-worker
    image: elastest/edm-alluxio:0.5.0
    # build: ./alluxio
    command: worker
    ports:
      - "29998"
      - "29999"
    links:
      - hdfs-namenode
      - alluxio-master
    # volumes:
    #   - ./tmpfiles:/tmpfiles
    ## change to your DOCKER_HOST
    # hostname: 192.168.99.100

    #    privileged: true         ### enable to use ramfs with docker. otherwise it will use disk
    environment:
      - ALLUXIO_MASTER_HOSTNAME=alluxio-master
      - ALLUXIO_RAM_FOLDER=/mnt/ramdisk
      - ALLUXIO_WORKER_MEMORY_SIZE=1GB
      - ALLUXIO_UNDERFS_ADDRESS=/underStorage
      # - ALLUXIO_UNDERFS_ADDRESS=hdfs://hdfs-namenode:9000
    volumes:
      - ./underStorage:/underStorage
      # - ./tmpfiles:/tmpfiles
    networks:
        - elastest


  alluxio-proxy:
    container_name: alluxio-proxy
    image: elastest/edm-alluxio:0.5.0
    # build: ./alluxio
    command: proxy
    ports:
      - 39999:39999
    links:
      - alluxio-worker
    # volumes:
    #   - ./tmpfiles:/tmpfiles
    ## change to your DOCKER_HOST
    # hostname: 192.168.99.100

    #    privileged: true         ### enable to use ramfs with docker. otherwise it will use disk
    environment:
      - ALLUXIO_MASTER_HOSTNAME=alluxio-master
      # - ALLUXIO_RAM_FOLDER=/mnt/ramdisk
      # - ALLUXIO_WORKER_MEMORY_SIZE=1GB
      # - ALLUXIO_UNDERFS_ADDRESS=hdfs://hdfs-namenode:9000
    volumes:
      - ./underStorage:/underStorage
      # - ./tmpfiles:/tmpfiles
    networks:
        - elastest


  elasticsearch:
    container_name: elasticsearch
    image: elastest/edm-elasticsearch:0.5.0
    # build: ./elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/backup:/backup
      - ./elasticsearch/esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - discovery.type=zen
      # use internal Docker round-robin DNS for unicast discovery
      - discovery.zen.ping.unicast.hosts=elasticsearch
    hostname: elasticsearch
    networks:
      - elastest


  esnode:
    # container_name: esnode
    image: elastest/edm-elasticsearch:0.5.0
    # build: ./elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/backup:/backup
      - ./elasticsearch/esdata2:/usr/share/elasticsearch/data
    ports:
      - "9200"
      - "9300"
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      # use internal Docker round-robin DNS for unicast discovery
      - discovery.type=zen
      - discovery.zen.ping.unicast.hosts=elasticsearch
    depends_on:
      - elasticsearch
    hostname: esnode
    networks:
      - elastest


  kibana:
    container_name: kibana
    image: elastest/edm-kibana:0.5.0
    # build: ./kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      # use internal Docker round-robin DNS for unicast discovery
      - discovery.type=zen
      - discovery.zen.ping.unicast.hosts=elasticsearch
    networks:
      - elastest
    depends_on:
      - esnode


  cerebro:
    container_name: cerebro
    image: elastest/edm-cerebro:0.5.0
    # build: ./cerebro
    volumes:
      - ./cerebro/config/conf:/opt/cerebro-0.6.5/conf
      - ./cerebro/logs:/opt/cerebro-0.6.5/logs
    depends_on:
      - elasticsearch
    ports:
      - 9400:9000
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    tty: true
    networks:
      - elastest
    depends_on:
      - elasticsearch

  mysql:
    container_name: mysql
    image: elastest/edm-mysql:0.5.0
    # build: ./mysql
    ports:
      - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: "elastestroot"
      MYSQL_DATABASE: "elastest"
      MYSQL_USER: elastest
      MYSQL_PASSWORD: elastest
    volumes:
      - elastest_mysql_data:/var/lib/mysql
      - ./mysql/backup:/docker-entrypoint-initdb.d
    # restart: always
    networks:
      - elastest
 
 
volumes:
  elastest_mysql_data:

networks:
  elastest:
    external: true
    # driver: bridge
